### ISSUE TITLE
`/_offline` not shown when offline

### ISSUE THREAD

**Issue by maximousblk** [shadowwalker/next-pwa#207]
# Summary

When offline, the cached pages work fine but when you visit an new (uncached) page, the `/_offline` page doesn't show up, instead the default chrome error page is shown.

# Versions

- `next-pwa`: `^5.2.15`
- `next`: `^10.2.0`

# How To Reproduce

1. Go to https://maximousblk-git-offline-maximousblk.vercel.app
2. let the service register
3. go offline (dev tools > application > service workers > offline)
4. go to a page that wasn't cached on the first load (`/posts/deno-for-javascript-beginners`)

source code at https://github.com/maximousblk/maximousblk.now.sh/pull/59
deployment at https://maximousblk-git-offline-maximousblk.vercel.app

# Expected Behavior

Should show the custom offline page

![image](https://user-images.githubusercontent.com/28438021/116548815-62619580-a912-11eb-8e91-77963af02ad6.png)

# Actual Behavior

Shows Google Chrome's default offline page

![image](https://user-images.githubusercontent.com/28438021/116548696-3e9e4f80-a912-11eb-8a14-7ae52fa8ba0e.png)

# Additional Context

n/a

**Comment by dryleaf** [comment]
Any updates on this issue?

**Comment by shadowwalker** [comment]
Upgrade to `5.2.16`

@maximousblk You can try these routes when offline to see if the issue is fixed: `/abc` and `/abc/def`. The `/abc` route got captured by your `pages/[slug].tsx` route, so it rendered through mdx instead. The `/abc/def` should fallback to your `/_offline` page

**Comment by maximousblk** [comment]
It's acting super weird now. It randomly selects an error page from `/_offline`, `/_error` or `<p>Oops! No Internet Connection</p>` and adds the whole page below the current page. [(video)](https://www.dropbox.com/s/d88aw4c6lzo874u/Maximous%20Black%20-%20Google%20Chrome%202021-04-30%2015-50-04.mp4?dl=0)


console errors:

a bunch of times this:
```red
TypeError: Cannot read property 'text' of undefined
    at y [as constructor] ([slug]-8bfa6923592137459b51.js?__WB_REVISION__=JOMtlp4Jq62YwzwB9pOkC:1)
    at y.D [as render] (commons-e1abd7d9af575ea860bc.js:1)
    at A (commons-e1abd7d9af575ea860bc.js:1)
    at x (commons-e1abd7d9af575ea860bc.js:1)
    at A (commons-e1abd7d9af575ea860bc.js:1)
    at x (commons-e1abd7d9af575ea860bc.js:1)
    at A (commons-e1abd7d9af575ea860bc.js:1)
    at x (commons-e1abd7d9af575ea860bc.js:1)
    at A (commons-e1abd7d9af575ea860bc.js:1)
    at x (commons-e1abd7d9af575ea860bc.js:1)
```

and then this:

```red
Uncaught (in promise) Error: Cancel rendering route
    at $ (main-8b942657d68a81710233.js:1)
    at main-8b942657d68a81710233.js:1
    at new Promise (<anonymous>)
    at ye (main-8b942657d68a81710233.js:1)
    at main-8b942657d68a81710233.js:1
```

**Comment by vitorcamachoo** [comment]
Im getting the following error when I add a page `_offline.tsx` on the building process for production:
`Cannot read property 'javascript' of undefined`

**Comment by shadowwalker** [comment]
@maximousblk Here you go: https://github.com/maximousblk/maximousblk.now.sh/pull/61

**Comment by maximousblk** [comment]
> https://github.com/maximousblk/maximousblk.now.sh/pull/61

while, that's one way to do it, the issue with that is I'm eventually going to remove the `/data` directory and move all the content to notion (waiting on the official api). So I was hoping I could keep all the website files in tsx and the actual content in mdx + json (for easy importing). so yeah the `/_offline` page needs to be in tsx. going with workaround != solution, I would still consider this issue unresolved.

also, 
I just upgrade to `next-pwa@5.2.18`, it does this:

![zGCtvkSmoo](https://user-images.githubusercontent.com/28438021/116774244-f2215400-aa78-11eb-8c8c-4729858f957a.gif)

**Comment by dryleaf** [comment]
Is this fixed now?

**Comment by maximousblk** [comment]
there is a [workaround](https://github.com/maximousblk/maximousblk.now.sh/pull/61) but no, it's not fixed yet

**Comment by aoshi321** [comment]
Hi

Wanted to know if this is has been fixed yet

thanks

**Comment by maximousblk** [comment]
@shadowwalker (and @aoshi321) this is still not fixed. I tried again with the latest version: https://github.com/maximousblk/maximousblk.me/pull/182 but the same issue still exists
